### ISSUE TITLE
[BUG] parsing bug (probably a regresson?)

### ISSUE THREAD

**Issue by NightMachinary** [victorperin/qr-scanner-cli#195]
```
❯ qrscanner ./IMG_4428.jpg                                                               1
Options:
      --version    Show version number                                 [boolean]
  -c, --clear      Clear output, just print the QR Code scan result
                                                      [boolean] [default: false]
  -p, --clipboard  Copy the qr code value to your clipboard
                                                      [boolean] [default: false]
  -o, --open       Open the qr code value in any browser or program if support
                   it                                 [boolean] [default: false]
      --help       Show help                                           [boolean]

Examples:
  qrscanner ./qrCode.jpg          
                                  ╔══════════════════════════════════════════╗
                                  ║                                          ║
                                  ║   This message is written in a QR Code   ║
                                  ║                                          ║
                                  ╚══════════════════════════════════════════╝
                                  
  qrscanner ./qrCode.jpg --clear
                                  This message is written in a QR Code

Unknown argument: ./IMG_4428.jpg
```

**Comment by victorperin** [comment]
Thanks, for the the feedback, I'm looking it, I think this error occours in the validation, provided by `yargs` package. Can you try renaming it the image to something like `image.jpg`, and test it? I'll help me understand better if this is the responsable.

Also, could be a version of yargs incorrectly installed, I say it because I've got this kind of error before and it was related to it.

**Comment by victorperin** [comment]
Also, can you provide the output of `qrscanner --version`, please?

**Comment by victorperin** [comment]
![image](https://user-images.githubusercontent.com/5847145/133343431-377518b6-6e0b-4808-b135-657c9f6a2939.png)

Confirmed, this is occouring in the latest version. Working on a patch. :)

**Comment by victorperin** [comment]
@NightMachinary, I think I've fixed this, by updating yargs dependency.

This is quite new to me, since only occours installing the package globaly, maybe It's necessary to run a post release test to check if everything is ok or so.

Please, feel free to check the next generated version (2.1.4), to check if the error persists.
